version: "3.9"  # optional since v1.27.0

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    domainname: khermann
    hostname: khermann
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always 
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        DOMAIN_NAME: ${DOMAIN_NAME}

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - wordpressdb:/var/lib/mysql
    networks:
      - inception
    environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        
volumes:
  wordpressdb:
    name: wordpressdb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khermann/data/wordpressdb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khermann/data/wordpress

networks:
  inception:
    driver: bridge
